# Generated by Django 4.2.16 on 2025-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='target_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
