# Generated by Django 4.2.16 on 2025-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playeroftheweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
