# Generated by Django 4.2.16 on 2025-02-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_player_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerOfTheWeek',
        ),
    ]
