i18next.init({
    lng: 'En',  // default language
    resources: {
      En: {

        translation: {
          "SIGN_UP_TITLE": "SIGN UP",
          "SIGN_IN_TITLE": "SIGN IN",
          "SIGN_UP": "Sign up",
          "SIGN_IN": "Sign in",
          "SETTINGS_TITLE": "Settings",
          "EMAIL": "Email",
          "Password": "Password",
          "PROFILE_IMAGE": "Profile Image",
          "NICKNAME": "Nickname",
          "FIRST_NAME": "First Name",
          "LAST_NAME": "Last Name",
          "SAVE_CHANGES": "Save Changes",
          "Enter_your_password": "Enter your password",
          "Enter_new_password": "Enter new password",
          "email": "Email",
          "choose_nickname": "Choose nickname",
          "Enter_first_name": "Enter your first name",
          "Enter_last_name": "Enter your last name",
          "upload_image": "Upload image",
          "have_account": "Have already an account?",
          "no_account": "Don't have an account?",
          "NEXT": "Next",
          "OR": "Or",
          "Nav_Game": "GAME",
          "Nav_Chat": "CHAT",
          "Nav_Users": "USERS",
          "Nav_About": "ABOUT",
          "MATCHES": "MATCHES",
          "WINS": "WINS",
          "LOSSES": "LOSSES",
          "Score": "SCORE :",
          "Game_text": " Dive into the excitement today! Master the game in just a few minutes, or team up with your friends for endless fun and thrilling competition! Whether you’re a newcomer or a seasoned player, there’s always something new to explore. Challenge yourself, strategize, and rise to the top of the leaderboard as you discover fresh ways to win!",
          "INVITE YOUR FRIENDS": "INVITE YOUR FRIENDS",
          "HOW TO PLAY": "HOW TO PLAY !",
           "Level": "LEVEL:",
           "SKILLS POINTS": "SKILLS POINTS:",
           "Your_Score": "YOUR_SCORE:",
           "Your_Level": "YOUR_LEVEL:",
           "view_profile": "view_profile", 
          "GAME_STORY": "Game Story",
          "HOW_TO_PLAY": "How to Play",
          "Game_story_content": "Dive into the exciting world of competitive ping pong! Whether you're challenging yourself in solo mode or facing off against friends in intense multiplayer matches, this game offers a fast-paced experience like no other. With realistic physics that perfectly capture the speed, spin, and bounce of the ball, every match feels like the real deal.As you play, you'll need to train your reflexes to react to lightning-fast shots, develop pinpoint accuracy, and master the art of spin to outsmart your opponents But that's just the beginning! Progress through various skill levels, each more challenging than the last, and rise through the ranks in competitive play. Whether you're a casual player looking for some fun or an aspiring pro determined to become the best, this game offers endless opportunities for growth and enjoyment",
          "How_to_play_content": "Use your paddle to bounce the ball across the table, aiming to outsmart your opponent with strategic shots and spins. With easy-to-learn controls and multiple difficulty levels, players of all skill levels can jump into the action.Challenge tougher opponents or compete with friends in fast-paced, exciting matches. The realistic gameplay keeps each rally intense and engaging, making every point a thrilling battle. Grab your paddle and dive into the ultimate ping pong showdown!",
          "Start Playing": "Start Playing",
          "Meet_the_team": "MEET THE TEAM TO SITE WEB THIS GAME",
          "Team_imane": "Developer front-end and design",
          "Team_nohaila": "Developer Game  and Designer",
          "Team_houda": "Developer back-end",
          "Team_fatimazahrsa": "Developer back-end",
          "Team_bouchra": "Developer Chat",
          "All Rights Reserved" : "&copy; 2024 Ping Pong Game. All Rights Reserved.",
          "how_to_play": "How to Play Ping Pong",
          "game_instructions": "Game Instructions",
          "step_1_title": "1. Serving",
          "step_1_description": "To serve, toss the ball up and hit it so it bounces on your side and then crosses the net.",
          "step_2_title": "2. Moving the Paddle",
          "step_2_description": "Use the arrow keys (left and right) to move your paddle and return the ball.",
          "step_3_title": "3. Scoring",
          "step_3_description": "Score when the opponent misses the ball. The game is played to 11 points.",
          "energy_and_skills_title": "Energy & Skill Points",
          "energy_and_skills_description": "Start with 100 Energy and 5 Skill Points. Use Skill Points to upgrade your paddle and skills during the game.",
          "start_playing_cta": "Click here to start playing",
          "USERS": "USERS",
          "NOT_FOUND_USERS": "NOT FOUND USERS",
          "FRIENDS": "FRIENDS",
          "NOT_FOUND_FRIENDS": "NOT FOUND FRIENDS",
          "view_profile": "View Profile",
          "Welcome_img": "IMAGES/WELCOME.png",
          "To_ping_pong_img": "IMAGES/TO-PING-PONG.png",
           "next_title_about": "IMAGES/EXPERIENCE-THE-FAST.png", 
           "Edit_Profile_TITLE": "Edit profile",
           "SETTINGS": "Settings",
          "VIEW_PROFILE": "View Profile",
          "LOG_OUT": "Log Out",
          "game_for_gamers": "IMAGES/GAME-FOR-THE-GAMERS.png",
          "enter_code_2FA_": "Enter 2FA Code",
          "enter_code_2FA": "Please enter the 6-digit code sent to your app.",
          "Submit_code_2FA": "Submit",
          "cancel_code_2FA": "Cancel",
          "Enter 2FA Code": "Enter 2FA Code",
          "start_adventure": "Start Your Adventure... in",
          "local_game_desc": "Play against a friend on the same device. A fun way to compete in person!",
           "tournament_desc": "Battle through multiple matches to become the ultimate champion!",
            "online_game_desc": "Play online and compete against players worldwide in real-time!",
           "play_button": "PLAY", 
           "replay_button": "REPLAY",
            "player1": "player 1",
            "player2": "player 2",
            "player-score": "SCORE",
            "PLAY_NEXT_button" : "Play Next Match",
            "game_local": "Game Local",
            "game_tournament": "Game Tournament",
            "game_remote": "Game Remote",
            "active-contact-name": "Select a contact",
            "discussions": "Discussions",
            "how_to_play": "How to Play Ping Pong",
        "game_instructions": "Game Instructions",
        "serving_step": "1. Serving",
        "serving_text": "To serve, toss the ball up and hit it so it bounces on your side and then crosses the net.",
        "moving_paddle_step": "2. Moving the Paddle",
        "moving_paddle_text": "Use the arrow keys (left and right) to move your paddle and return the ball.",
        "scoring_step": "3. Scoring",
        "scoring_text": "Score when the opponent misses the ball. The game is played to 11 points.",
        "energy_skill_points_step": "Energy & Skill Points",
        "energy_skill_points_text": "Start with 100 Energy and 5 Skill Points. Use Skill Points to upgrade your paddle and skills during the game.",
        "start_game_link": "Click here to start playing",
         "invitation_button": "Invitations",
         "start_tournament": "Start Tournament",
         "player1_label": "Player 1:",
         "player1_nickname": "Nickname for Player 1",
         "player1_alias_name": "Alias Name ",
         "player2_label": "Player 2:",
         "player2_nickname": "Nickname for Player 2",
         "player2_alias_name": "Alias Name ",
         "player3_label": "Player 3:",
         "player3_nickname": "Nickname for Player 3",
         "player3_alias_name": "Alias Name ",
         "player4_label": "Player 4:",
         "player4_nickname": "Nickname for Player 4",
         "player4_alias_name": "Alias Name for Player 4",
         "matches": "Matches",
         "loading": "Loading...",
         "waiting_match": "Waiting to get matched with another player...",
            "no_players": "No Available Players",
            "no_players_desc": "There are currently no players available to join the match.",
            "back_home": "Back to Home",
            "select_match_score": "Select Match Score",
            "choose_score": "Choose the score to finish the match:",
            "error_message": "Please enter a valid score between 1 and 13.",
            "confirm": "Confirm",
            "cancel": "Cancel",
            "join": "JOIN",
             "no_games": "No pending games available",
             "no_rankings": "No rankings available.",
             "img_ping_pong" : "IMAGES/PING-PONG-GAME.png",
             "img_ping_pong2" : "IMAGES/PING-PONG-GAME2.png"
        }
      },
      Fr: {
        translation: {
          "SIGN_UP_TITLE": "S'INSCRIRE",
          "SIGN_IN_TITLE": "SE CONNECTER",
          "SIGN_UP": "S'inscrire",
          "SIGN_IN": "Se connecter",
          "SETTINGS_TITLE": "Paramètres",
          "EMAIL": "Email",
          "Password": "Mot de passe",
          "PROFILE_IMAGE": "Image de profil",
          "NICKNAME": "Surnom",
          "FIRST_NAME": "Prénom",
          "LAST_NAME": "Nom",
          "SAVE_CHANGES": "Enregistrer les modifications",
          "Enter_your_password": "Entrez votre mot de passe",
          "Enter_new_password": "Entrez un nouveau mot de passe",
          "email": "Email",
          "choose_nickname": "Choisissez un surnom",
          "Enter_first_name": "Entrez votre prénom",
          "Enter_last_name": "Entrez votre nom",
          "upload_image": "Télécharger une image",
          "have_account": "Vous avez déjà un compte ?",
          "no_account": "Vous n'avez pas de compte ?",
          "NEXT": "Suivant",
          "OR": "Ou",
          "Nav_Game": "JEU",
          "Nav_Chat": "CHAT",
          "Nav_Users": "UTILISATEURS",
          "Nav_About": "À PROPOS",
          "MATCHES": "MATCHS",
          "WINS": "VICTOIRES",
          "LOSSES": "DÉFAITES",
          "Score": "SCORE :",
          "Game_text": "Plongez dans l'excitation dès aujourd'hui ! Maîtrisez le jeu en quelques minutes ou formez une équipe avec vos amis pour un plaisir sans fin et une compétition palpitante ! Que vous soyez un nouveau venu ou un joueur expérimenté, il y a toujours quelque chose de nouveau à découvrir. Relevez des défis, élaborez des stratégies et gravissez les échelons du classement tout en découvrant de nouvelles façons de gagner !",
          "INVITE YOUR FRIENDS": "INVITEZ VOS AMIS",
          "HOW TO PLAY": "COMMENT JOUER !",
          "Level": "NIVEAU :",
          "SKILLS POINTS": "PTS COMPÉT:",
          "Your_Score": "VOTRE_SCORE :",
          "Your_Level": "VOTRE_NIVEAU :",
          "GAME_STORY": "Histoire du Jeu",
          "HOW_TO_PLAY": "Comment Jouer",
          "Game_story_content": "Plongez dans le monde passionnant du ping-pong compétitif ! Que vous releviez des défis en mode solo ou affrontiez vos amis dans des matchs multijoueurs intenses, ce jeu offre une expérience palpitante unique. Avec une physique réaliste qui capture parfaitement la vitesse, l'effet et le rebond de la balle, chaque match semble réel. En jouant, vous devrez entraîner vos réflexes pour réagir à des tirs ultra-rapides, développer une précision extrême et maîtriser l'art des effets pour déjouer vos adversaires. Mais ce n'est que le début ! Progressez à travers différents niveaux de compétence, chacun plus difficile que le précédent, et grimpez les échelons dans des compétitions intenses. Que vous soyez un joueur occasionnel à la recherche de divertissement ou un futur pro déterminé à devenir le meilleur, ce jeu offre des opportunités infinies de progression et de plaisir.",
          "How_to_play_content": "Utilisez votre raquette pour renvoyer la balle sur la table, en visant à déjouer votre adversaire avec des coups stratégiques et des effets. Avec des commandes faciles à apprendre et plusieurs niveaux de difficulté, les joueurs de tous niveaux peuvent se lancer dans l'action. Affrontez des adversaires plus coriaces ou défiez vos amis dans des matchs rapides et excitants. Le gameplay réaliste rend chaque échange intense et captivant, transformant chaque point en une bataille palpitante. Prenez votre raquette et plongez dans l'ultime défi du ping-pong !",
          "Start Playing": "Commencer à Jouer",
          "Meet_the_team": "RENCONTREZ L'ÉQUIPE DE CE SITE WEB",
          "Team_imane": "Développeuse front-end et designer",
          "Team_nohaila": "Développeuse de jeu et designer",
          "Team_houda": "Développeuse back-end",
          "Team_fatimazahrsa": "Développeuse back-end",
          "Team_bouchra": "Développeuse Chat",
          "All Rights Reserved": "&copy; 2024 Jeu de Ping Pong. Tous droits réservés.",
          "how_to_play": "Comment jouer au Ping Pong",
          "game_instructions": "Instructions de jeu",
          "step_1_title": "1. Service",
          "step_1_description": "Pour servir, lancez la balle en l'air et frappez-la de manière à ce qu'elle rebondisse sur votre côté avant de traverser le filet.",
          "step_2_title": "2. Déplacement de la raquette",
          "step_2_description": "Utilisez les flèches (gauche et droite) pour déplacer votre raquette et renvoyer la balle.",
          "step_3_title": "3. Marquer des points",
          "step_3_description": "Marquez un point lorsque l'adversaire rate la balle. Le jeu se joue jusqu'à 11 points.",
          "energy_and_skills_title": "Énergie et Points de Compétence",
          "energy_and_skills_description": "Commencez avec 100 points d'énergie et 5 points de compétence. Utilisez ces points pour améliorer votre raquette et vos compétences pendant le jeu.",
          "start_playing_cta": "Cliquez ici pour commencer à jouer", 
          "USERS": "UTILISATEURS",
          "NOT_FOUND_USERS": "AUCUN UTILISATEUR TROUVÉ",
          "FRIENDS": "AMIS",
          "NOT_FOUND_FRIENDS": "AUCUN AMI TROUVÉ",
          "view_profile": "Voir le profil",
          "Welcome_img": "IMAGES/BIENVENUE.png",
          "To_ping_pong_img": "IMAGES/AU-PING-PONG.png",
          "Ping_pong_game": "IMAGES/JEU-DE-PING-.png",
          "game_for_gamers": "IMAGES/JEU-POUR-LES-JOUEURS.png",
          "next_title_about": "IMAGES/VIVEZ-L-ACTION.png",
          "Edit_Profile_TITLE": "Modifier le profil",
          "SETTINGS": "Paramètres",
          "VIEW_PROFILE": "Voir le profil",
           "LOG_OUT": "Se déconnecter" ,
           "enter_code_2FA_": "Entrez le code 2FA",
           "enter_code_2FA": "Veuillez entrer le code à 6 chiffres envoyé à votre app.",
           "Submit_code_2FA": "Soumettre",
           "cancel_code_2FA": "Annuler",
            "Enter 2FA Code": "Entrez le code 2FA",
            "start_adventure": "Commencez votre aventure... en",
            "local_game_desc": "Jouez contre un ami sur le même appareil. Un moyen amusant de rivaliser en personne!",
            "tournament_desc": "Affrontez plusieurs matchs pour devenir le champion ultime!",
            "online_game_desc": "Jouez en ligne et affrontez des joueurs du monde entier en temps réel!",
            "play_button": "JOUER",
            "replay_button": "REJOUER",
            "player1": "Joueur 1",
            "player2": "Joueur 2",
            "player-score": "SCORE" ,
             "PLAY_NEXT_button" : "Jouer le Prochain Match",
            "game_local": "Jeu Local",
            "game_tournament": "Tournoi de Jeu",
            "game_remote": "Jeu à Distance",
            "active-contact-name": "Sélectionner un contact",
            "discussions": "Discussions",
            "how_to_play": "Comment Jouer au Ping-Pong",
        "game_instructions": "Instructions du Jeu",
        "serving_step": "1. Service",
        "serving_text": "Pour servir, lancez la balle et frappez-la de manière à ce qu'elle rebondisse de votre côté et traverse le filet.",
        "moving_paddle_step": "2. Déplacement de la Palette",
        "moving_paddle_text": "Utilisez les touches fléchées (gauche et droite) pour déplacer votre palette et renvoyer la balle.",
        "scoring_step": "3. Marquer des Points",
        "scoring_text": "Gagnez des points lorsque l'adversaire rate la balle. Le jeu se joue jusqu'à 11 points.",
        "energy_skill_points_step": "Énergie & Points de Compétence",
        "energy_skill_points_text": "Commencez avec 100 Énergie et 5 Points de Compétence. Utilisez les Points de Compétence pour améliorer votre palette et vos compétences pendant le jeu.",
        "start_game_link": "Cliquez ici pour commencer à jouer",
         "invitation_button": "Invitations",
         "start_tournament": "Démarrer le tournoi",
         "player1_label": "Joueur 1:",
         "player1_nickname": "Surnom du joueur 1",
         "player1_alias_name": "Alias du joueur 1",
         "player2_label": "Joueur 2:",
         "player2_nickname": "Surnom du joueur 2",
         "player2_alias_name": "Alias du joueur 2",
         "player3_label": "Joueur 3:",
         "player3_nickname": "Surnom du joueur 3",
         "player3_alias_name": "Alias du joueur 3",
         "player4_label": "Joueur 4:",
         "player4_nickname": "Surnom du joueur 4",
         "player4_alias_name": "Alias du joueur 4",
         "matches": "Matchs",
         "loading": "Chargement..." ,
          "waiting_match": "En attente d'être jumelé avec un autre joueur...",
          "no_players": "Aucun joueur disponible",
          "no_players_desc": "Il n'y a actuellement aucun joueur disponible pour rejoindre le match.",
          "back_home": "Retour à l'accueil",
          "select_match_score": "Sélectionner le score du match",
        "choose_score": "Choisissez le score pour terminer le match :",
        "error_message": "Veuillez entrer un score valide entre 1 et 13.",
        "confirm": "Confirmer",
        "cancel": "Annuler",
        "join": "REJOINDRE",
         "no_games": "Aucun jeu en attente disponible",
         "no_rankings": "Aucun classement disponible.",
          "img_ping_pong" : "IMAGES/JEU-DE-PING-PONG.png",
           "img_ping_pong2" : "IMAGES/JEU-DE-PING-PONG2.png"


        }},
        Es: {
          translation: 
          {
            "SIGN_UP_TITLE": "REGÍSTRATE",
            "SIGN_IN_TITLE": "INICIAR SESIÓN",
            "SIGN_UP": "Registrarse",
            "SIGN_IN": "Iniciar sesión",
            "SETTINGS_TITLE": "Configuración",
            "EMAIL": "Correo electrónico",
            "Password": "Contraseña",
            "PROFILE_IMAGE": "Imagen de perfil",
            "NICKNAME": "Apodo",
            "FIRST_NAME": "Nombre",
            "LAST_NAME": "Apellido",
            "SAVE_CHANGES": "Guardar cambios",
            "Enter_your_password": "Ingrese su contraseña",
            "Enter_new_password": "Ingrese nueva contraseña",
            "email": "Correo electrónico",
            "choose_nickname": "Elija un apodo",
            "Enter_first_name": "Ingrese su nombre",
            "Enter_last_name": "Ingrese su apellido",
            "upload_image": "Subir imagen",
            "have_account": "¿Ya tienes una cuenta?",
            "no_account": "¿No tienes una cuenta?",
            "NEXT": "Siguiente",
            "OR": "O",
            "Nav_Game": "JUEGO",
            "Nav_Chat": "CHAT",
            "Nav_Users": "USUARIOS",
            "Nav_About": "SOBRE NOSOTROS",
            "MATCHES": "PARTIDOS",
            "WINS": "VICTORIAS",
            "LOSSES": "DERROTAS",
            "Score": "PUNTOS :",
            "Game_text": " ¡Sumérgete en la emoción hoy! Domina el juego en solo unos minutos o únete a tus amigos para una diversión interminable y emocionante competencia.",
            "INVITE YOUR FRIENDS": "INVITAR A TUS AMIGOS",
            "HOW TO PLAY": "CÓMO JUGAR",
            "Level": "NIVEL:",
            "SKILLS POINTS": "PUNTOS DE HABILIDAD:",
            "Your_Score": "TU PUNTUACIÓN:",
            "Your_Level": "TU NIVEL:",
            "view_profile": "Ver perfil",
            "GAME_STORY": "Historia del juego",
            "HOW_TO_PLAY": "Cómo jugar",
            "Game_story_content": "¡Plongez dans le mundo passionnant du ping-pong compétitif! Que vous releviez des défis en mode solo ou affrontiez vos amis dans des partidos multijoueurs intensos, ce jeu offre una experiencia palpitante única. Avec une physique réaliste qui capture parfaitement la vitesse, l'effet et le rebond de la balle, cada match semble réel. Al jugar, deberás introducir tus reflejos para reaccionar con los tiros ultrarrápidos, desarrollar una precisión extrema y maîtriser el arte de los efectos para disfrutar de tus adversarios. ¡Mas ce n'est que le debut! Progrese a través de diferentes niveles de competencia, cada vez más difícil que el anterior, y emprenda los niveles en las competiciones intensas. Que seas un jugador ocasional en la búsqueda de diversión o un futuro pro determinado a alcanzar el mejor, este juego ofrece infinitas oportunidades de progresión y placer.",
            "How_to_play_content": "Usa tu paleta para hacer rebotar la pelota sobre la mesa, con el objetivo de burlar a tu oponente con tiros y giros estratégicos. Con controles fáciles de aprender y múltiples niveles de dificultad, los jugadores de todos los niveles pueden saltar a la acción. Desafía a oponentes más duros o compite con amigos en partidas emocionantes y de ritmo rápido. La jugabilidad realista mantiene cada jugada intensa y atractiva, haciendo de cada punto una batalla emocionante. ¡Coge tu remo y sumérgete en el enfrentamiento definitivo de ping pong!",
            "Start Playing": "Comienza a jugar",
            "Meet_the_team": "CONOCE EL EQUIPO",
            "Team_imane": "Desarrollador Front-end y Diseño",
            "Team_nohaila": "Desarrollador del juego y diseñador",
            "Team_houda": "Desarrollador Back-end",
            "Team_fatimazahrsa": "Desarrollador Back-end",
            "Team_bouchra": "Desarrollador de chat",
            "All Rights Reserved" : "&copy; 2024 Ping Pong Game. Todos los derechos reservados.",
            "how_to_play": "Cómo jugar Ping Pong",
            "game_instructions": "Instrucciones del juego",
            "step_1_title": "1. Servicio",
            "step_1_description": "Para servir, lanza la pelota hacia arriba y golpéala para que rebote en tu lado y luego cruce la red.",
            "step_2_title": "2. Mover la paleta",
            "step_2_description": "Usa las teclas de flecha (izquierda y derecha) para mover tu paleta y devolver la pelota.",
            "step_3_title": "3. Puntuación",
            "step_3_description": "Gana cuando el oponente no consiga devolver la pelota. El juego se juega hasta los 11 puntos.",
            "energy_and_skills_title": "Energía y Puntos de Habilidad",
            "energy_and_skills_description": "Comienza con 100 Energía y 5 Puntos de Habilidad. Usa los puntos de habilidad para mejorar tu paleta y habilidades durante el juego.",
            "start_playing_cta": "Haz clic aquí para comenzar a jugar",
            "USERS": "USUARIOS",
            "NOT_FOUND_USERS": "USUARIOS NO ENCONTRADOS",
            "FRIENDS": "AMIGOS",
            "NOT_FOUND_FRIENDS": "AMIGOS NO ENCONTRADOS",
            "view_profile": "Ver perfil",
            "Welcome_img": "IMAGES/BIENVENIDOS.png",
            "To_ping_pong_img": "IMAGES/A-PING-PONG.png",
            "Ping_pong_game": "IMAGES/JEU-DE-PING-.png",
            "game_for_gamers": "IMAGES/JUEGO-PARA-JUGADORE.png",
            "next_title_about": "IMAGES/VIVE-LA-ACCI-N-A-UN-RITMO.png",
             "Edit_Profile_TITLE": "Editar perfil",
             "SETTINGS": "Configuración",
            "VIEW_PROFILE": "Ver perfil",
            "LOG_OUT": "Cerrar sesión",
            "enter_code_2FA_": "Ingrese el código 2FA",
            "enter_code_2FA": "Por favor, introduzca el código de 6 dígitos enviado a su app.",
            "Submit_code_2FA": "Enviar",
            "cancel_code_2FA": "Cancelar",
            "Enter 2FA Code": "Ingrese el código 2FA",
            "start_adventure": "Comienza tu aventura... en",
             "local_game_desc": "Juega contra un amigo en el mismo dispositivo. ¡Una forma divertida de competir en persona!",
            "tournament_desc": "¡Compite en múltiples partidos para convertirte en el campeón definitivo!",
            "online_game_desc": "¡Juega en línea y compite contra jugadores de todo el mundo en tiempo real!",
            "play_button": "JUGAR", 
            "replay_button": "REPETIR",
            "player1": "Jugador 1",
            "player2": "Jugador 2",
            "player-score": "PUNTUACIÓN",
            "PLAY_NEXT_button" : "Jugar el Próximo Partido",
            "game_local": "Juego Local",
            "game_tournament": "Torneo de Juego",
            "game_remote": "Juego Remoto",
            "active-contact-name": "Seleccionar un contacto",
            "discussions": "Discusiones",
            "how_to_play": "Cómo Jugar al Ping Pong",
        "game_instructions": "Instrucciones del Juego",
        "serving_step": "1. Servicio",
        "serving_text": "Para servir, lanza la pelota hacia arriba y golpéala para que rebote en tu lado y cruce la red.",
        "moving_paddle_step": "2. Moviendo la Paleta",
        "moving_paddle_text": "Usa las teclas de flecha (izquierda y derecha) para mover la paleta y devolver la pelota.",
        "scoring_step": "3. Anotar",
        "scoring_text": "Anota cuando el oponente falle la pelota. El juego se juega hasta 11 puntos.",
        "energy_skill_points_step": "Energía y Puntos de Habilidad",
        "energy_skill_points_text": "Comienza con 100 Energía y 5 Puntos de Habilidad. Usa los Puntos de Habilidad para mejorar tu paleta y habilidades durante el juego.",
        "start_game_link": "Haz clic aquí para comenzar a jugar",
         "invitation_button": "Invitaciones",
         "start_tournament": "Iniciar torneo",
         "player1_label": "Jugador 1:",
         "player1_nickname": "Apodo del Jugador 1",
         "player1_alias_name": "Alias del Jugador 1",
         "player2_label": "Jugador 2:",
         "player2_nickname": "Apodo del Jugador 2",
         "player2_alias_name": "Alias del Jugador 2",
         "player3_label": "Jugador 3:",
         "player3_nickname": "Apodo del Jugador 3",
         "player3_alias_name": "Alias del Jugador 3",
         "player4_label": "Jugador 4:",
         "player4_nickname": "Apodo del Jugador 4",
         "player4_alias_name": "Alias del Jugador 4",
         "matches": "Partidos",
         "loading": "Cargando..." ,
         "waiting_match": "Esperando para emparejarse con otro jugador...",
          "no_players": "No hay jugadores disponibles",
          "no_players_desc": "Actualmente no hay jugadores disponibles para unirse a la partida.",
          "back_home": "Volver a inicio",
          "select_match_score": "Seleccionar puntuación del partido",
          "choose_score": "Elige la puntuación para terminar el partido:",
          "error_message": "Por favor, ingrese una puntuación válida entre 1 y 13.",
          "confirm": "Confirmar",
          "cancel": "Cancelar",
          "join": "UNIRSE",
          "no_games": "No hay juegos pendientes disponibles",
           "no_rankings_es": "No hay clasificaciones disponibles.",
            "img_ping_pong" : "IMAGES/JUEGO-DE-PING-PONG_spanish.png",
             "img_ping_pong2" : "IMAGES/JUEGO-DE-PING-PONG_spanish2.png"
  
          
          }
        },
    }
  });

function updateContent() 
{
  const elements = document.querySelectorAll('[data-i18n]');
  const img_welcome = document.getElementsByClassName('WELCOME')[0];
  const img_ping_pong = document.getElementsByClassName('ping_pong_game')[0];
  const img_ping_pong2 = document.getElementsByClassName('game-title-image')[0];
  const img_to_ping = document.getElementsByClassName('TO-PING-PONG')[0];
  const next_title_about = document.getElementsByClassName('next_title')[0];
  const game_for_gamers = document.getElementsByClassName('game_for')[0];
  if (next_title_about) next_title_about.src = i18next.t("next_title_about");
  if (img_welcome) img_welcome.src = i18next.t("Welcome_img");
  if (img_welcome) img_welcome.src = i18next.t("Welcome_img");
  if (img_ping_pong) img_ping_pong.src = i18next.t("img_ping_pong");
  if (img_ping_pong2) img_ping_pong2.src = i18next.t("img_ping_pong2");
  if (game_for_gamers) game_for_gamers.src = i18next.t("game_for_gamers");
  elements.forEach(el => {
  const key = el.getAttribute('data-i18n');
  el.textContent = i18next.t(key);
});
document.querySelectorAll('[data-i18n_placeholder]').forEach(el => {
  const key = el.getAttribute('data-i18n_placeholder');
  el.placeholder = i18next.t(key);
});
}

i18next.changeLanguage(localStorage.getItem("Language"), () => 
{
updateContent();
});