# Generated by Django 4.2.16 on 2024-12-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invit',
            field=models.CharField(choices=[('none', 'none'), ('add', 'add'), ('added', 'added')], default='none', max_length=10),
        ),
    ]
