# Generated by Django 4.2.16 on 2024-12-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_customuser_invit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invit',
            field=models.CharField(choices=[('none', 'none'), ('added', 'added'), ('receive_invit', 'receive_invit')], default='none', max_length=30),
        ),
    ]
