# Generated by Django 5.1.2 on 2024-12-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
