# Generated by Django 5.1.2 on 2024-12-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_seen_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_send',
            field=models.BooleanField(default=False),
        ),
    ]
