# Generated by Django 5.1.2 on 2025-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_seen_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocker',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user2',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocked_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocker_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='user1_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='user2_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
