# Generated by Django 5.1.2 on 2025-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_blockeduser_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
