# Generated by Django 5.1.2 on 2025-02-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
    ]
