# Generated by Django 5.1.2 on 2025-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_recipients_room_is_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('warning', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_notification',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
